### ISSUE TITLE
Does this work on smart phones?

### ISSUE THREAD

**Issue by vishal-h** [rniemeyer/knockout-sortable#16]
Does sortable work on mobile / smart phones / iPad etc. I've tried on iPad / Android powered phones without success. I am not able to select individual items. Whenever I tap on one item the whole list gets selected and drag/drop doesn't happen.

**Comment by pscheit** [comment]
is my phone dump? Android 4.4.2 in Chrome does not work anymore?

**Comment by lampshaj** [comment]
The fiddles referenced are no longer compiling correctly.

**Comment by rniemeyer** [comment]
@lampshaj  - I updated the dependencies on the fiddle: https://jsfiddle.net/rniemeyer/vrU6Z/ and it is still working on mobile (easiest to load https://jsfiddle.net/rniemeyer/vrU6Z/show on mobile). I did grab the touch punch script from here: https://github.com/RWAP/jquery-ui-touch-punch rather than the original repo, as this was a slightly more up-to-date fork of the project.

**Comment by lampshaj** [comment]
@rniemeyer Thank you! Touch punch and Sortable are working great together in my project.

**Comment by rniemeyer** [comment]
@lampshaj - ooh nice, good to hear!
